//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuSatisOtomasyonu.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class siparisler
    {
        public int siparisID { get; set; }
        public int musteriID { get; set; }
        public string durum { get; set; }
        public int tutar { get; set; }
        public System.DateTime tarih { get; set; }
    
        public virtual musteriler musteriler { get; set; }
    }
}
